p8105_hw2_zw2974
================
Zihan Wu
9/27/2023

# Problem 1

## Importing and cleaning data tables

## For pols-month.csv

``` r
polsmonth = read_csv("data/pols-month.csv") 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
polsmonth_clean = polsmonth |> 
  janitor::clean_names()  |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(month = replace(month, month == "01", "January"))  |> 
  mutate(month = replace(month, month == "02", "February"))  |> 
  mutate(month = replace(month, month == "03", "March"))  |> 
  mutate(month = replace(month, month == "04", "April"))  |> 
  mutate(month = replace(month, month == "05", "May"))  |> 
  mutate(month = replace(month, month == "06", "June"))  |> 
  mutate(month = replace(month, month == "07", "July"))  |> 
  mutate(month = replace(month, month == "08", "August"))  |> 
  mutate(month = replace(month, month == "09", "September"))  |> 
  mutate(month = replace(month, month == "10", "October"))  |> 
  mutate(month = replace(month, month == "11", "November"))  |> 
  mutate(month = replace(month, month == "12", "December"))  |> 
  pivot_longer(cols = c("prez_dem", "prez_gop"), 
               names_to = "president",
               values_to = "value") |>
  filter(value == 1) |>
  mutate(president = case_when(
    president == "prez_gop" ~ "gop",
    president == "prez_dem" ~ "dem"
  )) |>
  select(-value, -day)
```

## For snp.csv

``` r
snp = read_csv("data/snp.csv") 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_clean = snp |> 
  janitor::clean_names()  |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  mutate(year = case_when(
                 nchar(year) == 1 ~ paste0("200", year),
                 nchar(year) == 2 & as.integer(year) <= 23 ~ paste0("20", year),
                 nchar(year) == 2 & as.integer(year) > 23 ~ paste0("19", year),
                 TRUE ~ year
             )) |> 
  mutate(month = factor(month, levels = 1:12, labels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))) |> 
  select(year, month, close)
```

## For unemployment.csv

``` r
unemployment = read_csv("data/unemployment.csv")
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_clean = unemployment |> 
  janitor::clean_names() |> 
  pivot_longer(cols = jan:dec, names_to = "month", values_to = "unemployment_rate") |> 
  mutate(month = replace(month, month == "jan", "January"))  |> 
  mutate(month = replace(month, month == "feb", "February"))  |> 
  mutate(month = replace(month, month == "mar", "March"))  |> 
  mutate(month = replace(month, month == "apr", "April"))  |> 
  mutate(month = replace(month, month == "may", "May"))  |> 
  mutate(month = replace(month, month == "jun", "June"))  |> 
  mutate(month = replace(month, month == "jul", "July"))  |> 
  mutate(month = replace(month, month == "aug", "August"))  |> 
  mutate(month = replace(month, month == "sep", "September"))  |> 
  mutate(month = replace(month, month == "oct", "October"))  |> 
  mutate(month = replace(month, month == "nov", "November"))  |> 
  mutate(month = replace(month, month == "dec", "December")) |> 
  select(year, month, unemployment_rate)
```

# Problem 2

## Read and clean the Mr. Trash Wheel sheet:

``` r
mr_trash_wheel = read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N549") |> 
  janitor::clean_names() |> 
  mutate(homes_powered = weight_tons * 500 /30) |> 
  mutate(type = "Mr.") |> 
  mutate(year = as.integer(year)) |> 
  drop_na(dumpster)
```

## Read and clean the Professor Trash Wheel sheet:

``` r
professor_df = read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M96") |> 
  janitor::clean_names() |> 
  mutate(homes_powered = weight_tons * 500 /30) |> 
  mutate(type = "Professor") |> 
  mutate(year = as.integer(year)) |> 
  drop_na(dumpster)
```

## Read and clean the Gwynnda Trash Wheel sheet:

``` r
gwynnda_df = read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", range = "A2:K108") |> 
  janitor::clean_names() |> 
  mutate(homes_powered = weight_tons * 500 /30) |>
  mutate(type = "Gwynnda") |> 
  mutate(year = as.integer(year)) |>
  drop_na(dumpster)
```

## Read and clean the Professor Trash Wheel sheet:

``` r
combination = bind_rows(mr_trash_wheel, professor_df, gwynnda_df) |> 
  relocate(type)

combination
```

    ## # A tibble: 747 × 16
    ##    type  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1 Mr.          1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2 Mr.          2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3 Mr.          3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4 Mr.          4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5 Mr.          5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6 Mr.          6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7 Mr.          7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8 Mr.          8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9 Mr.          9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10 Mr.         10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 737 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, sports_balls <dbl>, homes_powered <dbl>,
    ## #   plastic_bags <dbl>

## Write a paragraph about these data:

Number of observations: 747

Numbers of variables: 16

Names of key variables: type, dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, grocery_bags, chip_bags, sports_balls, homes_powered,
plastic_bags

Total weight of trash collected by Professor Trash Wheel: 190.12

Total number of cigarette butts collected by Gwynnda in July of 2021:
1.63^{4}

# Problem 3

## Import, clean, and tidy the dataset of baseline demographics

- sex and APOE4 carrier status are appropriate encoded (i.e. not
  numeric)
- remove any participants who do not meet the stated inclusion criteria
  (i.e. no MCI at baseline)

``` r
baseline = read_csv("data/MCI_baseline.csv", skip = 1) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex,
      1 ~ "Male",
      0 ~ "Female")
    ) |> 
  mutate(
    apoe4 = case_match(
      apoe4,
      1 ~ "APOE4 carrier",
      0 ~ "APOE4 non-carrier")
    )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_df = baseline |> 
  filter(age_at_onset != ".")
```

## Discuss important steps in the import process and relevant features of the dataset

483 participants were recruited

97 participants develop MCI

Average baseline age: 65.6113402

``` r
woman_APOE4 = baseline_df |> 
  filter(sex == "Female" & apoe4 == "APOE4 carrier") |> 
  count()
```

Proportion of women in the study are APOE4 carriers: 0.3092784

## Import, clean, and tidy the dataset of longitudinally observed biomarker values

``` r
amyloid = read_csv("data/mci_amyloid.csv", skip = 1) |> 
  janitor::clean_names() |> 
  subset(
    baseline != "NA" & baseline != "Na"
  ) |> 
  rename(
    id = study_id
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
view(amyloid)
```

## Check whether some participants appear in only the baseline or amyloid datasets, and comment on your findings

``` r
merge_df = left_join(baseline_df, amyloid, by = "id")

baseline_only = merge_df |> 
  subset(
    is.na(merge_df$baseline)
  )
view(baseline_only)
```

There are 3 participants appear in only the baseline datasets.

``` r
merge_df2 =
  right_join(baseline_df, amyloid, by = "id")

amyloid_only=
  merge_df2|>
  subset(
    is.na(merge_df2$age_at_onset))
```

There are 391 participants appear in only the amyloid datasets.

## Combine the demographic and biomarker datasets so that only participants who appear in both datasets are retained, and briefly describe the resulting dataset

From the dataset, wer can discover there are94 participants while only
66 can accomplish the process

## Export the result as a CSV to your data directory

``` r
write_csv(both,"Both mci_baseline and mci_amyloid")
write_csv(complete,"Complete participants")
```
